name: Databricks CI/CD

on:
  push:
    branches:
      - develop
      - release
      - main
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  black:
    uses: ./.github/workflows/black.yml
  coverage:
    uses: ./.github/workflows/code-coverage.yml
  gitleaks:
    uses: ./.github/workflows/gitleaks.yml


  deploy:
    runs-on: ubuntu-latest
    needs: [lint, black, coverage, gitleaks]
    defaults:
      run:
        working-directory: dbx_bundle

    # Map branch -> GitHub environment (dev, qa, prod)
    environment: ${{ github.ref == 'refs/heads/main' && 'dev' || github.ref == 'refs/heads/release' && 'qa' || 'dev' }}

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI (new)
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Check Databricks CLI
        run: databricks version

      - name: Deploy Notebooks to Environment
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            databricks workspace import-dir dbx_bundle "/Users/tushar@hemaliriaangmail.onmicrosoft.com/dev2"
          elif [[ "${GITHUB_REF##*/}" == "release" ]]; then
            databricks workspace import-dir dbx_bundle /Repos/qa/dbx_bundle
          fi
