name: Databricks CI/CD

on:
  push:
    branches:
      - develop
      - release
      - main
  pull_request:

jobs:
  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install black flake8

      - name: Run Black (format check)
        run: black --check dbx_bundle

      - name: Run Flake8 (lint check)
        run: flake8 dbx_bundle

  deploy:
    name: Deploy to Databricks
    runs-on: ubuntu-latest
    needs: lint-and-format

    # Map branch -> GitHub environment (dev, qa, prod)
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/release' && 'qa' || 'dev' }}

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Deploy Notebooks to Environment
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            databricks workspace import_dir -o dbx_bundle /Repos/dev/dbx_bundle
          elif [[ "${GITHUB_REF##*/}" == "release" ]]; then
            databricks workspace import_dir -o dbx_bundle /Repos/qa/dbx_bundle
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            databricks workspace import_dir -o dbx_bundle /Repos/prod/dbx_bundle
          fi
