name: Databricks Asset Bundle CI/CD

on:
  push:
    branches:
      - develop
      - release
      - main
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters
        run: pip install black flake8

      - name: Run Black (format check)
        run: black --check dbx_bundle

      - name: Run Flake8 (lint check)
        run: flake8 dbx_bundle

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-format
    defaults:
      run:
        working-directory: dbx_bundle

    # Map GitHub branch -> GitHub Environment
    environment: ${{ github.ref == 'refs/heads/main' && 'dev' || github.ref == 'refs/heads/release' && 'qa' || 'dev' }}

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI (new)
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/cli/main/install.sh | sh
          echo "$HOME/.databricks/bin" >> $GITHUB_PATH

      - name: Check Databricks CLI
        run: databricks version

      - name: Deploy Asset Bundle
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            databricks bundle deploy -t dev
          elif [[ "${GITHUB_REF##*/}" == "release" ]]; then
            databricks bundle deploy -t qa
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            databricks bundle deploy -t prod
          fi
