name: Gitleaks Scan

on:
  workflow_call:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        run: |
          mkdir -p gitleaks-results
          gitleaks detect --source . --no-git -r gitleaks-results/gitleaks.json || true

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-results
